// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTc1qG02Tobv8FI8Hy2Ko3STz-b5BOa4E',
    appId: '1:122741019764:android:d3ea2bc75f409f9f28ed21',
    messagingSenderId: '122741019764',
    projectId: 'auction-sheet-app',
    storageBucket: 'auction-sheet-app.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlXVt3JZ-STPjEqQoflXB4ONRCDAqflkM',
    appId: '1:122741019764:web:a2a4dbd0a6bda6bb28ed21',
    messagingSenderId: '122741019764',
    projectId: 'auction-sheet-app',
    authDomain: 'auction-sheet-app.firebaseapp.com',
    storageBucket: 'auction-sheet-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH0-kjKqEqyVsW-vJh8OuJPcA-tlEGPjM',
    appId: '1:122741019764:ios:69a3999f9a911f6b28ed21',
    messagingSenderId: '122741019764',
    projectId: 'auction-sheet-app',
    storageBucket: 'auction-sheet-app.firebasestorage.app',
    androidClientId: '122741019764-88g8226aes1mhu3tsqc4co2v19inlh7m.apps.googleusercontent.com',
    iosClientId: '122741019764-0jirvb1pdsi4o84u80mj17021mu522e7.apps.googleusercontent.com',
    iosBundleId: 'com.example.auctionSheet',
  );
}
